use_frameworks!

platform :ios, '8.0'

target 'SSNetworkTool_Example' do
  pod 'SSNetworkTool', :path => '../'

  target 'SSNetworkTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
